"""Reusable UI primitives for Evidence Gate. case36 enforces the three-color palette.

case22 UX CHANGE — WHY:
Blind Test 02 showed that a long stack of full Claim cards does not scale to real papers. case21 uses
an issue-first Master–Detail workspace: the queue is compact, while the selected Claim receives the
wide evidence/contract area. Accent colors remain Navy/Teal/Amber; neutrals are surfaces only.
"""

# [수정: 전문가3] 2026-09-23 case36
# 종류: 오류수정
# 재현 방법: core/ui.py의 HEX 값을 검색하면 3색 외 회색·녹색 surface 값이 다수 존재했다.
# 변경 전: Navy/Teal/Amber 외 별도 HEX 회색·연녹색·연황색 사용.
# 변경 후: 직접 HEX는 3색만 사용하고 surface/line/muted는 같은 3색의 alpha 표현으로 파생.
# 왜: 팀의 3색 시각 규칙을 코드 수준에서 강제하기 위해.
# 영향: 상태 의미는 라벨·아이콘·테두리와 함께 유지. case52에서 청록의 흰색 대비를 5.57:1로 측정하고 작은 글자 기준을 만족하도록 조정.
# [수정: 전문가3] 2026-09-25 case52
# 종류: 오류수정 / 재현 방법: 기존 청록 작은 글자의 흰색 대비 3.32:1 / 변경 전: 4.5:1 미만 / 변경 후: #0B756A는 5.57:1, CTA 글자는 흰색 / 왜: 작은 상태 라벨과 버튼 읽기 / 영향: 3색 팔레트 유지.
PALETTE={"navy":"#17324D","teal":"#0B756A","amber":"#E9C46A"}
CSS=r"""
<style>
:root{--navy:#17324D;--teal:#0B756A;--amber:#E9C46A;--muted:rgba(23,50,77,.68);--line:rgba(23,50,77,.18);--surface:rgba(23,50,77,.035);--soft:rgba(11,117,106,.055)}
.block-container,[data-testid="stMainBlockContainer"]{padding-top:1.25rem;padding-bottom:3rem;max-width:1380px!important;width:min(92%,1380px)!important;margin:0 auto!important}
h1,h2,h3{color:var(--navy)}[data-testid="stSidebar"]{background:rgba(23,50,77,.035);border-right:1px solid rgba(23,50,77,.18)}
.stButton>button{border-radius:10px;font-weight:750;min-height:2.6rem}.stButton>button[kind="primary"],button[data-testid="stBaseButton-primary"]{background:var(--teal)!important;border-color:var(--teal)!important;color:white!important}
.eg-hero,.eg-panel,.eg-card,.eg-value,.eg-start{border:1px solid var(--line);border-radius:16px;background:rgba(23,50,77,.018)}.eg-hero{padding:17px 22px;margin-bottom:12px}.eg-title{font-size:1.7rem;font-weight:850;color:var(--navy)}.eg-sub,.eg-muted{color:var(--muted);font-size:.91rem;line-height:1.5}
.eg-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:8px 0 14px}.eg-summary>div{border:1px solid var(--line);border-radius:12px;padding:12px;background:rgba(23,50,77,.018)}.eg-summary-k{font-size:.75rem;color:var(--muted);font-weight:750}.eg-summary-v{font-size:1.45rem;color:var(--navy);font-weight:850}.eg-summary-five{grid-template-columns:repeat(5,1fr)}
.eg-selected{border:1px solid var(--line);border-radius:16px;background:rgba(23,50,77,.018);padding:20px 22px;margin-bottom:10px}.eg-claim{font-size:1.2rem;font-weight:850;color:var(--navy);margin:8px 0}.eg-pill{display:inline-block;padding:5px 10px;border-radius:999px;font-size:.76rem;font-weight:850}.eg-passpill{background:rgba(11,117,106,.10);color:var(--teal)}.eg-warnpill{background:rgba(233,196,106,.18);color:var(--navy);border:1px solid var(--amber)}.eg-blockpill{background:var(--surface);color:var(--navy);border:1px solid var(--navy)}
.eg-contract{border-left:4px solid var(--teal);background:var(--soft);padding:13px 15px;border-radius:8px;margin:10px 0}.eg-contract.blocked{border-left-color:var(--navy);background:var(--surface)}.eg-contract-type{font-size:.72rem;color:var(--muted);font-weight:850;letter-spacing:.05em}.eg-contract-main{font-size:1.02rem;color:var(--navy);font-weight:800;margin-top:3px}.eg-contract-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px 18px;margin-top:8px}.eg-contract-field{display:flex;justify-content:space-between;gap:12px;border-top:1px solid rgba(23,50,77,.14);padding-top:7px;color:var(--navy)}.eg-contract-field span{color:var(--muted);font-size:.8rem}.eg-contract-field b{text-align:right;font-size:.88rem}
.eg-gates{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:10px 0 14px}.eg-gate{border:1px solid var(--line);border-radius:12px;padding:11px;background:rgba(23,50,77,.018)}.eg-gate-name{font-size:.69rem;font-weight:850;color:var(--muted);letter-spacing:.04em}.eg-gate-title{font-weight:800;color:var(--navy);margin-top:4px}.eg-pass{border-left:4px solid var(--teal)}.eg-review,.eg-warn,.eg-fail{border-left:4px solid var(--amber)}.eg-fail{background:rgba(233,196,106,.18)}.eg-blocked{border-left:4px solid var(--navy);background:var(--surface)}.eg-na{border-left:4px solid var(--line)}
.eg-result-hero{border:1px solid var(--line);border-radius:16px;background:rgba(23,50,77,.018);padding:18px 22px;margin:10px 0}.eg-result-flow{display:grid;grid-template-columns:1fr auto 1fr;align-items:end;gap:18px;max-width:650px}.eg-result-num{font-size:2.25rem;font-weight:900;color:var(--navy);line-height:1}.eg-result-arrow{font-size:2rem;color:var(--teal);font-weight:900}.eg-result-note{margin-top:10px;color:var(--muted);font-size:.9rem}.eg-result{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:10px 0}.eg-result>div{padding:10px 0}.eg-label{font-size:.75rem;color:var(--muted);font-weight:750}.eg-big{font-size:1.65rem;color:var(--navy);font-weight:850}.eg-alert{border-left:4px solid var(--amber);background:rgba(233,196,106,.18);padding:12px 14px;border-radius:8px;color:var(--navy);font-weight:700}.eg-ok{border-left:4px solid var(--teal);background:rgba(11,117,106,.10);padding:12px 14px;border-radius:8px;color:var(--navy);font-weight:700}
.eg-lineage{border:1px solid var(--line);border-radius:14px;padding:14px 16px}.eg-line{display:grid;grid-template-columns:145px 1fr;gap:12px;padding:7px 0;border-bottom:1px solid rgba(23,50,77,.12)}.eg-line:last-child{border-bottom:0}.eg-line-key{color:var(--muted);font-weight:700}.eg-line-val{color:var(--navy);font-weight:650;word-break:break-word}
.eg-landing{text-align:center;padding:10px 0 2px}.eg-landing h2{font-size:2rem;margin:.25rem 0 .5rem}.eg-landing p{max-width:800px;margin:0 auto;color:var(--muted);font-size:1rem;line-height:1.65}.eg-flow{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:20px 0 16px}.eg-step{border:1px solid var(--line);border-radius:14px;background:rgba(23,50,77,.018);padding:16px 12px;min-height:108px;text-align:left}.eg-step-no{color:var(--teal);font-size:.75rem;font-weight:850;letter-spacing:.08em}.eg-step-title{color:var(--navy);font-weight:850;margin:7px 0 3px}.eg-step-desc{color:var(--muted);font-size:.82rem;line-height:1.45}.eg-start{padding:18px 24px;margin:10px auto 18px;max-width:880px;text-align:center}.eg-values{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.eg-value{padding:17px;text-align:left}.eg-value-title{font-weight:850;color:var(--navy);margin-bottom:5px}.eg-value-desc{font-size:.86rem;line-height:1.5;color:var(--muted)}
@media(max-width:1100px){.eg-summary-five{grid-template-columns:repeat(3,1fr)}.eg-contract-fields{grid-template-columns:1fr}}
@media(max-width:980px){.block-container,[data-testid="stMainBlockContainer"]{width:96%!important}.eg-flow{grid-template-columns:1fr 1fr}.eg-values,.eg-summary,.eg-result{grid-template-columns:1fr 1fr}.eg-gates{grid-template-columns:1fr 1fr}}
.eg-provenance{display:grid;grid-template-columns:120px 1fr auto;gap:12px;align-items:center;border:1px solid var(--line);border-left:4px solid var(--amber);border-radius:10px;padding:10px 12px;margin:8px 0;background:rgba(23,50,77,.018)}.eg-provenance b{color:var(--navy)}.eg-source{font-size:.78rem;font-weight:850;border:1px solid var(--amber);border-radius:999px;padding:4px 8px;color:var(--navy)}
/* case93 UX: narrow screens retain readable cards and touch targets; test_case93_navigation. */
@media(max-width:640px){.eg-summary,.eg-summary-five,.eg-gates,.eg-result,.eg-values,.eg-flow{grid-template-columns:1fr}.eg-provenance,.eg-line{grid-template-columns:1fr}.eg-result-flow{gap:8px}.eg-result-num{font-size:1.65rem}.stButton>button{min-height:44px}.block-container,[data-testid="stMainBlockContainer"]{padding-left:.6rem;padding-right:.6rem}}
</style>"""
LANDING_HTML="""
<div style="display:none">보고서의 주장을 원자료까지 추적해 다시 검증합니다. · 01 INPUT · 02 LINK · 03 ANALYZE · 04 VERIFY · 05 DECIDE · 주장 추적 · 원자료 재검산 · 판단 이력 보존</div><div class="eg-landing"><h2>논문 속 숫자, 원자료로 다시 확인하세요.</h2><p>확인할 문장과 자료를 연결하면 어떤 계산을 했는지, 숫자가 같은지, 아직 모르는 점이 무엇인지 보여드립니다. 처음이라면 왼쪽의 ‘쉬운 연구 도우미’에서 과제 하나로 시작하세요.</p></div>
<div class="eg-flow"><div class="eg-step"><div class="eg-step-no">01 INPUT</div><div class="eg-step-title">보고서 입력</div><div class="eg-step-desc">PDF 원문과 페이지를 보존해 Claim을 찾습니다.</div></div><div class="eg-step"><div class="eg-step-no">02 CONTRACT</div><div class="eg-step-title">검증 계약 생성</div><div class="eg-step-desc">평균·비교·상관·회귀·범위 Claim을 서로 다른 계약으로 만듭니다.</div></div><div class="eg-step"><div class="eg-step-no">03 SPECIFY</div><div class="eg-step-title">근거·분석 명세 확인</div><div class="eg-step-desc">필수 근거 또는 분석정책이 없으면 계산을 차단합니다.</div></div><div class="eg-step"><div class="eg-step-no">04 EXECUTE</div><div class="eg-step-title">통계 재실행</div><div class="eg-step-desc">확정된 계약만 규칙·통계 엔진이 실행합니다.</div></div><div class="eg-step"><div class="eg-step-no">05 DECIDE</div><div class="eg-step-title">사람 최종 판단</div><div class="eg-step-desc">수정·재검증·승인을 Claim ID로 기록합니다.</div></div></div>
<div class="eg-start"><b>근거관문 시작하기</b><br><span class="eg-muted">왼쪽에서 PDF와 CSV를 연결하거나 예시 데이터로 검증 흐름을 체험하세요.</span></div>
<div class="eg-values"><div class="eg-value"><div class="eg-value-title">재현 가능성 · Reproducibility</div><div class="eg-value-desc">같은 데이터와 확인된 조건이면 제3자가 동일 계산을 다시 실행할 수 있습니다.</div></div><div class="eg-value"><div class="eg-value-title">추적 가능성 · Traceability</div><div class="eg-value-desc">Claim → 원문 → 데이터 → 필터 → 방법 → 결과를 하나의 계보로 연결합니다.</div></div><div class="eg-value"><div class="eg-value-title">감사 가능성 · Auditability</div><div class="eg-value-desc">사람의 근거 확인·수정·재검증·승인을 Claim ID 단위로 보존합니다.</div></div></div>"""
